### ISSUE TITLE
Permgen Leak in TomEE.

### ISSUE THREAD

**Issue by tonywestonuk** [mybatis/cdi#26] opened 2015-10-18 16:09 UTC
MyBatis CDI causes memory leak in TomEE.   After investigation, I have tracked this down to an instance of org.apache.ibatis.executor.ErrorContext that is created during MyBatisBean.create().

To Fix,  ErrorContext.instance().reset()   needs to be added just before MyBatisBean.create() returns.

As a workaround, I have added ErrorContext.instance().reset();   to my SqlSessionFactoryProvider class after the SqlSessionFactory has been built.

**Comment by emacarron** [comment] 2015-10-18 16:48
Hi @tonywestonuk can you make the change yourself and send a pull request?

**Comment by hazendaz** [comment] 2016-04-23 17:06
@emacarron I took a look around in guice since it would seem logical that if this has a leak there is one over there too.  And there certainly was and it was fixed long ago.  I have added the above code where noted and will perform a pull request but not completely sure if that is the right spot so I will let that sit until further review.  I know I'll want to run some live tests on this and I'm still about 3 months off from finally getting switched over to using mybatis-cdi over some internal cdi solution I created years ago.

**Comment by emacarron** [comment] 2016-04-23 17:27
@hazendaz Ok. Do the change and let me know. I will have a look at it and tell you. Thank you!

**Comment by hazendaz** [comment] 2016-08-27 16:38
This still needs tested but I went ahead and merged it since guice module has same code and we are getting backed up on outstanding version updates ;)  I still plan to use this version when I get time.  Last I tested I was running into some odd issues (possibly unrelated) but in my actual use case we are still a ways off from switching from home grown version of this to the official copy.  And it seems I cannot find time these days to really get in there so I just going to push forwards and when I do get to this I'll confirm and close this out then.  That is unless someone else tests first and can close this ;)

**Comment by hazendaz** [comment] 2016-11-28 01:19
I'm going to go ahead and release this with the fix noted.  I'll do some higher level tests after release.  These days it's hard to get usage in place without jumping lots of hoops so will just release then follow-up on some testing...

**Comment by mnesarco** [comment] 2017-01-20 16:17
It looks like this is fixed in commit 59937fe can we close this issue?

**Comment by mnesarco** [comment] 2017-02-17 17:51
Hi @hazendaz , can we close this issue? it seems that you have fixed this long time ago.

**Comment by hazendaz** [comment] 2017-02-18 02:33
I didn't test the solution but I think based on guice fix of the same that the issue is resolved.

@tonywestonuk Is this something you can test again on latest beta and let us know if this is still an issue?

**Comment by mnesarco** [comment] 2017-02-22 15:23
Fixed in 59937fe1596a6e2c4dda9a2bf7697c7b34c60a4f

**Closed by mnesarco** 2017-02-22 15:23 UTC
