### ISSUE TITLE
Inject SqlSession/Mapper to EJB with CDI

### ISSUE THREAD

**Issue by zappee** [mybatis/cdi#61] opened 2017-04-23 18:19 UTC
There is an error during injecting SqlSession or Mapper to EJB.

Please find details here:
http://stackoverflow.com/questions/43574276/mybatis-cdi-container-managed-transaction

**Comment by mnesarco** [comment] 2017-04-23 22:13
@zappee please put the details here.

**Comment by zappee** [comment] 2017-06-16 18:23
So now it is clear whaut is the issue.
I have created two projects, they are uploaded to git.

1) WEB application (https://github.com/zappee/mybatis-web-demo)
Simple war inside an ear.
It works lik a charm.

2) EE application (https://github.com/zappee/mybatis-ee-demo)
The ear contains a common jar, a stateless ejb and a war file.
EJB calls MyBatis stuff.
WAR uses EJB.

The MyBatis related files (config, session factory) are in EJB.

The issue here is somehow the EE container expects SessionFactory in WAR but it is not there and a "There are no SqlSessionFactory producers" exception appears. There is no MyBatis related code in WAR, the only think there is calling the EJB which contains the MyBatis related code.

I do not want to put MyBatis code to war, I would like to keep it in EJBs and I would like to call EJBs from WAR.

How MyBatis CDI works in this scenario?
Could you please check my example projects which demonstrate the issue?

**Comment by mnesarco** [comment] 2017-06-17 01:11
Hi @zappee 
Do you have a bean.xml file inside the EJB jar? If you have any artifact with injectable CDI stuff, you have to include a bean.xml file inside the correct locations ie. META-INF/ or WEB-INF/ . In this case you will need one inside the EJB jar META-INF and another inside the war WEB-INF.

**Comment by zappee** [comment] 2017-06-17 10:22
Sorry, I missed to add beans.xml to this application. I added them to the right places but there is no impact. I get the same error.

Source code of EE Demo Application in git has been updated.

**Comment by zappee** [comment] 2017-06-17 11:26
I have added a new Jersy rest modules (*.war) with a simple GET rest method to the ear. It contains beans.xml as well. When I call the GET url from browser I get the same error:

org.mybatis.cdi.MybatisCdiConfigurationException: There are no SqlSessionFactory producers properly configured.
	at org.mybatis.cdi.CDIUtils.findSqlSessionFactory(CDIUtils.java:55)
	at org.mybatis.cdi.SerializableMapperProxy.getMapper(SerializableMapperProxy.java:57)
	at org.mybatis.cdi.SerializableMapperProxy.<init>(SerializableMapperProxy.java:44)
	at org.mybatis.cdi.MyBatisBean.create(MyBatisBean.java:116)
	at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:70)
        ...

I do not understand the concept behind it. Why this exception appears in war modules? There is nothing related to MyBatis in WARs.

mybatis-3.4.4.jar and mybatis-cdi-1.0.0.jar are in the *.ear/lib directory.

Is something missing from my war files or it is a cdi bug?

**Comment by hazendaz** [comment] 2017-06-18 04:39
@mnesarco 

I looked at this and I think it has something to do with this line of code below.  Although I admit I have almost no idea on all of this...

```
    return Proxy.newProxyInstance(SqlSessionFactory.class.getClassLoader(), new Class[] { this.type },
        new SerializableMapperProxy(this, creationalContext));
```

With the setup on this one, the EAR/lib has SqlSessionFactory but the classes we need are in the EJB/lib.  Thus the WAR/lib cannot see inside there.  In this case, as reported the WAR shouldn't even attempt to do this lookup as it's not appropriate given the context.  I suspect because of mybatis libs being shared in this case that no matter what is added it's going to attempt to do the same.  I went as far as adding dummy class to get past the issue but then the mapper fails to register later.

Any of that even get close to diagnosing this?

**Comment by zappee** [comment] 2017-06-18 10:32
JSON Rest module demo is here: https://github.com/zappee/mybatis-ee-demo/tree/mybatis-demo-rest_module.

**Comment by mnesarco** [comment] 2017-06-18 18:01
@zappee @hazendaz 
I have tested the demo project https://github.com/zappee/mybatis-ee-demo on wildfly 10 and it works out of the box. Maybe a Payara specific issue?

**Comment by zappee** [comment] 2017-06-18 20:47
What a surprise!
I tested my demo on Wildfly 10.1.0 yes, it works...
I am going to ask help from Payara guys.

**Comment by Zolerii** [comment] 2017-06-19 05:22
Is there any way to know if CDIUtils is using getBeans(String name) or getBeans(Type beanType, Annotation... qualifiers) to get the Bean Set in Payara?

**Comment by mnesarco** [comment] 2017-06-21 15:34
@Zolerii 

https://github.com/mybatis/cdi/blob/master/src/main/java/org/mybatis/cdi/CDIUtils.java#L68

 beans = beanManager.getBeans(SqlSessionFactory.class, qualifiers.toArray(new Annotation[] {}));

**Comment by mnesarco** [comment] 2017-07-02 16:54
@zappee @Zolerii 
Hi Guys, do you have any news about this issue?

**Comment by mnesarco** [comment] 2017-07-02 17:05
@zappee @Zolerii @hazendaz 
Thanks to OndreJ from Payara for its detailed description of the problem: https://github.com/payara/Payara/issues/1688#issuecomment-309732522, so this is not a bug related to mybatis-cdi. He suggest to put all common CDI beans in a separated jar in <EAR>/lib to make it visible to all modules (ejbs and wars). I will leave this open for a while, so we can continue analyzing and talking about.

**Comment by zappee** [comment] 2017-07-16 15:41
Sorry for the late reply. As @OndrejM suggested I moved mybatis related stuff to ear/lib/commons.jar and mybatis-cdi has been started to do its job. So it works now.

I updated my demo project on git as well: [mybatis-ee-demo](https://github.com/zappee/mybatis-ee-demo). 

This is the structure of my EAR:

*.ear
  |- lib
  |    |- my-commons.jar
  |    |    |- @mapper interface
  |    |    |- SqlSessionFactory
  |    |
  |    |- mybatis-3.4.4.jar
  |    |- mybatis-cdi-1.0.0.jar
  |    |- ...
  |
  |- META-INF
  |   |- application.xml
  |    
  |- ejb.jar
  |    |- META-INF
  |    |    |- beans.xml
  |    |
  |    |- log4j.properties
  |    |- mybatis.xml
  |
  |- *.war
       |- WEB-INF
       |    |- beans.xml
       |    |- classes
       |    |- lib

**Comment by mnesarco** [comment] 2017-07-17 04:20
Great news @zappee . So I am going to close this now. But this issue contains valuable information. I will add some notices in the documentation. Thanks for your contributions.

**Closed by mnesarco** 2017-07-17 04:20 UTC
